### ISSUE TITLE
Bug: JSON parse error from a server-side implementation 

### ISSUE THREAD

**Issue by draczihper** [Bulalu/pimp-UI#1]
After generating images 2 times then trying the third attempt, you get an in app error that says ```Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data```. I think because the server-side response for maxed out usage limit is not a JSON object as it supposed to be as when an image is generated. If so the limits are only 2 somehow for me and whenever I try the third there's an error. 

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
Browser:  Mozilla Firefox 121.0.1

**Comment by Bulalu** [comment]
good catch, i look into this
I'll also be open sourcing the server side code so we can debug/ make it stronger together 🤝

**Comment by draczihper** [comment]
That's a good move.

**Comment by draczihper** [comment]
Issue #1 fixed with error handling of status code 429.
